# Generated by Django 3.2.6 on 2021-08-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('singer', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=50)),
                ('weeks_on_chart', models.CharField(max_length=100)),
                ('last_week', models.CharField(max_length=100)),
                ('peak_date', models.CharField(max_length=100)),
                ('peak_rank', models.CharField(max_length=10)),
                ('debut_date', models.CharField(max_length=100)),
                ('debut_rank', models.CharField(max_length=10)),
            ],
        ),
    ]
